version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - echo Build started on `date`
      - echo Installing dependencies...
      - npm ci
  build:
    commands:
      - echo Build started on `date`
      - echo Building the application...
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
  base-directory: dist
  name: nippo-app-artifacts

cache:
  paths:
    - 'node_modules/**/*'